spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          batch_size: 20
        default_batch_fetch_size: 20
        format_sql: true

  datasource:
    url: jdbc:h2:mem:voting
    username: ${DB_USER}
    password: ${DB_PASSWORD}

logging:
  level:
    root: warn
    com.crevan.votesystem: debug

server.servlet:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
